mixin.perf.clear_mixin_classinfo=true
mixin.perf.deduplicate_climate_parameters=true
mixin.perf.deduplicate_location=true
mixin.perf.dynamic_entity_renderers=true
mixin.perf.dynamic_languages=true
mixin.perf.dynamic_resources=false
mixin.perf.faster_item_rendering=true
