name = "Coxford Survival"
author = "Coxford Network"
version = "0.1.0"
description = "Both-sides performance pack. Same mod list on the server and on every client."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c24cee052912d49a759a9fda2b0e2651d1e320e55cb8b4ceba91fea9991bba97"

[versions]
minecraft = "26.2"
fabric = "0.19.5"
