config_version=1
onboarding_finished=true
muted=true
disabled=true
hide_icons=true
group_hud_icon_scale=2.0
group_player_icon_orientation=HORIZONTAL
group_player_icon_pos_x=-30
group_player_icon_pos_y=-16
hud_icon_pos_x=-32
hud_icon_pos_y=22
hud_icon_scale=1.0
