# Don't change this! Version used to track needed updates.
version = 0
devEnvironmentMixins = false

[performance]
perfDynamicResources = true
perfReleaseProtochunks = true
perfNetworkOptimizations = true
perfNetworkEnhancements = true
particleTrackingRangeBlocks = 48
featureFastIpPing = true
featureForceCloseLoadingScreen = true

[troubleshooting]
spamThreadDump = false
sparkProfileLaunch = false
integratedServerWatchdog = true
clearMixinClassinfo = false

[expertOnly]

[expertOnly.bugfixes]
bugfixChunkDeadlock = false
bugfixCofhCoreCrash = true
bugfixConcurrency = true
bugfixEndIslandOverflow = true
bugfixExtraExperimentalScreen = true
bugfixMissingBlockEntities = false
bugfixPaperChunkPatches = true
bugfixRecipeBookTypeDesync = true
bugfixRestoreOldDragonMovement = false
bugfixSingleplayerKeepaliveKick = true
bugfixUnsafeModdedShapeCaches = true
bugfixWorldLeaks = true
bugfixWorldScreenSkipped = true

[expertOnly.perf]
perfAttributeSupplierDedup = true
perfBadOptimizationsDebugRendererCulling = true
perfBadOptimizationsParticleCulling = true
perfBadOptimizationsSkipNonDemoTutorial = true
perfBadOptimizationsToastCulling = true
perfBadOptimizationsZeroFovCalculation = true
perfBlockCounting = true
perfBlockstatePropertyaccess = true
perfCacheBlockstateCacheArrays = true
perfCacheProfileTextureUrl = true
perfCacheStrongholds = true
perfChunkMeshing = true
perfCompactBitStorage = true
perfCompactEntityModels = true
perfCompactImposterprotochunks = true
perfCompactMojangRegistries = true
perfCompressUnihexFont = true
perfDatapackReloadExceptions = true
perfDedicatedReloadExecutor = true
perfDeduplicateAdvancementPredicates = true
perfDeduplicateClimateParameters = true
perfDeduplicateLocation = true
perfDeduplicateNbtStrings = true
perfDeduplicateWallShapes = true
perfDynamicDfu = true
perfDynamicEntityRenderers = true
perfDynamicLanguages = true
perfDynamicSounds = true
perfDynamicStructureManager = true
perfEncoderCacheLeak = true
perfFastBitstorage = true
perfFastBlockEntityRemoval = true
perfFastPalette = true
perfFasterCommandSuggestions = true
perfFasterItemRendering = true
perfFasterTextureStitching = true
perfGameThreadPriority = true
perfGetblock = true
perfLazySearchTreeRegistry = true
perfMemoizeCreativeTabBuild = true
perfModelOptimizations = true
perfMobSpawning = true
perfPoiLookup = true
perfMojangRegistrySize = true
perfRandomTicking = true
perfRemoveBiomeTemperatureCache = true
perfResourcepacks = true
perfStateDefinitionConstruct = true
perfTagIdCaching = true
perfThreadPriorities = true
perfThreadUnsafeRandom = true
perfTickingChunkAlloc = true
perfWorldgenAllocation = true

[expertOnly.misc]
core = true
featureBlockentityIncorrectThread = false
featureBranding = true
featureCauseLagByDisablingThreads = false
featureDirectStackTrace = false
featureMcfunctionProfiling = true
featureMeasureTime = true
featureRemoveChatSigning = false
featureRemoveTelemetry = true
featureSparkProfileWorldJoin = true
featureStalledChunkLoadDetection = false
featureSuppressNarratorStacktrace = true
snapshotEasterEgg = true